apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: task-app
type: Opaque
data:
  mongo-root-username: bW9uZ29hZG1pbg==  # base64 of your username
  mongo-root-password: cGFzc3dvcmQxMjM=  # base64 of your password
